Program(
  TypeDeclaration(
    myInt,
    NamedTypeExpression(
      int)),
  ProcedureDeclaration(
    callbyval,
    Parameters(
      ParameterDeclaration(
        x,
        NamedTypeExpression(
          int),
        false),
      ParameterDeclaration(
        y,
        NamedTypeExpression(
          myInt),
        false)),
    Variables(),
    Body(
      AssignStatement(
        NamedVariable(
          x),
        BinaryExpression(
          ADD,
          VariableExpression(
            NamedVariable(
              x)),
          IntLiteral(
            1))),
      AssignStatement(
        NamedVariable(
          y),
        BinaryExpression(
          ADD,
          VariableExpression(
            NamedVariable(
              y)),
          IntLiteral(
            1))))),
  TypeDeclaration(
    vektor,
    ArrayTypeExpression(
      NamedTypeExpression(
        myInt),
      10)),
  ProcedureDeclaration(
    callbyref,
    Parameters(
      ParameterDeclaration(
        x,
        NamedTypeExpression(
          int),
        true),
      ParameterDeclaration(
        y,
        NamedTypeExpression(
          myInt),
        true)),
    Variables(),
    Body(
      AssignStatement(
        NamedVariable(
          x),
        BinaryExpression(
          ADD,
          VariableExpression(
            NamedVariable(
              x)),
          IntLiteral(
            1))),
      AssignStatement(
        NamedVariable(
          y),
        BinaryExpression(
          ADD,
          VariableExpression(
            NamedVariable(
              y)),
          IntLiteral(
            1))))),
  ProcedureDeclaration(
    callArray,
    Parameters(
      ParameterDeclaration(
        v,
        NamedTypeExpression(
          vektor),
        true)),
    Variables(),
    Body(
      AssignStatement(
        ArrayAccess(
          NamedVariable(
            v),
          IntLiteral(
            0)),
        IntLiteral(
          99)),
      AssignStatement(
        ArrayAccess(
          NamedVariable(
            v),
          IntLiteral(
            4)),
        IntLiteral(
          66)))),
  TypeDeclaration(
    matrix,
    ArrayTypeExpression(
      ArrayTypeExpression(
        NamedTypeExpression(
          int),
        8),
      8)),
  TypeDeclaration(
    tensor,
    ArrayTypeExpression(
      NamedTypeExpression(
        matrix),
      16)),
  ProcedureDeclaration(
    callRecursive,
    Parameters(
      ParameterDeclaration(
        n,
        NamedTypeExpression(
          int),
        false),
      ParameterDeclaration(
        res,
        NamedTypeExpression(
          myInt),
        true)),
    Variables(),
    Body(
      IfStatement(
        BinaryExpression(
          LSE,
          VariableExpression(
            NamedVariable(
              n)),
          IntLiteral(
            10)),
        CompoundStatement(
          CallStatement(
            callRecursive,
            Arguments(
              BinaryExpression(
                ADD,
                VariableExpression(
                  NamedVariable(
                    n)),
                IntLiteral(
                  1)),
              VariableExpression(
                NamedVariable(
                  res))))),
        EmptyStatement()),
      AssignStatement(
        NamedVariable(
          res),
        BinaryExpression(
          ADD,
          VariableExpression(
            NamedVariable(
              res)),
          VariableExpression(
            NamedVariable(
              n)))),
      AssignStatement(
        NamedVariable(
          n),
        BinaryExpression(
          ADD,
          VariableExpression(
            NamedVariable(
              n)),
          IntLiteral(
            1))))),
  ProcedureDeclaration(
    manyargs,
    Parameters(
      ParameterDeclaration(
        i,
        NamedTypeExpression(
          int),
        false),
      ParameterDeclaration(
        j,
        NamedTypeExpression(
          myInt),
        false),
      ParameterDeclaration(
        k,
        NamedTypeExpression(
          tensor),
        true),
      ParameterDeclaration(
        l,
        NamedTypeExpression(
          myInt),
        true)),
    Variables(),
    Body(
      CallStatement(
        callRecursive,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)))),
      IfStatement(
        BinaryExpression(
          GRT,
          VariableExpression(
            NamedVariable(
              i)),
          IntLiteral(
            0)),
        CallStatement(
          manyargs,
          Arguments(
            BinaryExpression(
              SUB,
              VariableExpression(
                NamedVariable(
                  i)),
              IntLiteral(
                1)),
            VariableExpression(
              NamedVariable(
                l)),
            VariableExpression(
              NamedVariable(
                k)),
            VariableExpression(
              NamedVariable(
                j)))),
        EmptyStatement()),
      IfStatement(
        BinaryExpression(
          EQU,
          VariableExpression(
            NamedVariable(
              i)),
          IntLiteral(
            0)),
        CallStatement(
          check,
          Arguments(
            VariableExpression(
              NamedVariable(
                i)),
            VariableExpression(
              NamedVariable(
                j)),
            IntLiteral(
              0),
            IntLiteral(
              67))),
        EmptyStatement()),
      IfStatement(
        BinaryExpression(
          EQU,
          VariableExpression(
            NamedVariable(
              i)),
          IntLiteral(
            1)),
        CallStatement(
          check,
          Arguments(
            VariableExpression(
              NamedVariable(
                i)),
            VariableExpression(
              NamedVariable(
                j)),
            IntLiteral(
              1),
            IntLiteral(
              69))),
        EmptyStatement()),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))))),
  ProcedureDeclaration(
    hide,
    Parameters(),
    Variables(
      VariableDeclaration(
        myInt,
        NamedTypeExpression(
          myInt)),
      VariableDeclaration(
        hide,
        NamedTypeExpression(
          int))),
    Body()),
  ProcedureDeclaration(
    main,
    Parameters(),
    Variables(
      VariableDeclaration(
        i,
        NamedTypeExpression(
          int)),
      VariableDeclaration(
        j,
        NamedTypeExpression(
          myInt)),
      VariableDeclaration(
        k,
        ArrayTypeExpression(
          NamedTypeExpression(
            myInt),
          10)),
      VariableDeclaration(
        l,
        ArrayTypeExpression(
          ArrayTypeExpression(
            NamedTypeExpression(
              int),
            8),
          8)),
      VariableDeclaration(
        m,
        ArrayTypeExpression(
          NamedTypeExpression(
            vektor),
          5)),
      VariableDeclaration(
        n,
        NamedTypeExpression(
          vektor)),
      VariableDeclaration(
        t,
        NamedTypeExpression(
          tensor))),
    Body(
      CallStatement(
        ausgabe,
        Arguments(
          IntLiteral(
            1))),
      AssignStatement(
        NamedVariable(
          i),
        BinaryExpression(
          SUB,
          BinaryExpression(
            SUB,
            IntLiteral(
              1),
            IntLiteral(
              2)),
          IntLiteral(
            3))),
      AssignStatement(
        NamedVariable(
          j),
        BinaryExpression(
          SUB,
          BinaryExpression(
            ADD,
            IntLiteral(
              1),
            BinaryExpression(
              MUL,
              IntLiteral(
                2),
              BinaryExpression(
                SUB,
                IntLiteral(
                  0),
                VariableExpression(
                  NamedVariable(
                    i))))),
          BinaryExpression(
            MUL,
            BinaryExpression(
              DIV,
              BinaryExpression(
                DIV,
                BinaryExpression(
                  SUB,
                  IntLiteral(
                    7),
                  IntLiteral(
                    77)),
                IntLiteral(
                  7)),
              IntLiteral(
                5)),
            BinaryExpression(
              MUL,
              IntLiteral(
                2),
              BinaryExpression(
                SUB,
                IntLiteral(
                  1),
                BinaryExpression(
                  ADD,
                  IntLiteral(
                    2),
                  BinaryExpression(
                    SUB,
                    IntLiteral(
                      4),
                    BinaryExpression(
                      ADD,
                      IntLiteral(
                        5),
                      BinaryExpression(
                        SUB,
                        IntLiteral(
                          4),
                        BinaryExpression(
                          ADD,
                          IntLiteral(
                            3),
                          BinaryExpression(
                            SUB,
                            IntLiteral(
                              2),
                            BinaryExpression(
                              MUL,
                              IntLiteral(
                                1),
                              BinaryExpression(
                                ADD,
                                IntLiteral(
                                  1),
                                BinaryExpression(
                                  SUB,
                                  IntLiteral(
                                    3),
                                  BinaryExpression(
                                    SUB,
                                    IntLiteral(
                                      4),
                                    IntLiteral(
                                      5)))))))))))))))),
      CallStatement(
        check,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)),
          BinaryExpression(
            SUB,
            IntLiteral(
              0),
            IntLiteral(
              4)),
          IntLiteral(
            25))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      AssignStatement(
        NamedVariable(
          i),
        IntLiteral(
          43690)),
      AssignStatement(
        NamedVariable(
          j),
        BinaryExpression(
          SUB,
          IntLiteral(
            48059),
          BinaryExpression(
            MUL,
            IntLiteral(
              65),
            IntLiteral(
              2)))),
      CallStatement(
        check,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)),
          IntLiteral(
            43690),
          IntLiteral(
            47929))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      AssignStatement(
        NamedVariable(
          i),
        BinaryExpression(
          SUB,
          IntLiteral(
            0),
          IntLiteral(
            1))),
      AssignStatement(
        NamedVariable(
          j),
        IntLiteral(
          32)),
      AssignStatement(
        ArrayAccess(
          ArrayAccess(
            NamedVariable(
              m),
            BinaryExpression(
              SUB,
              IntLiteral(
                0),
              IntLiteral(
                0))),
          IntLiteral(
            7)),
        BinaryExpression(
          SUB,
          VariableExpression(
            NamedVariable(
              i)),
          BinaryExpression(
            SUB,
            IntLiteral(
              0),
            VariableExpression(
              NamedVariable(
                i))))),
      AssignStatement(
        ArrayAccess(
          ArrayAccess(
            NamedVariable(
              m),
            BinaryExpression(
              SUB,
              IntLiteral(
                0),
              VariableExpression(
                NamedVariable(
                  i)))),
          IntLiteral(
            8)),
        IntLiteral(
          135)),
      AssignStatement(
        ArrayAccess(
          ArrayAccess(
            NamedVariable(
              m),
            BinaryExpression(
              ADD,
              IntLiteral(
                1),
              IntLiteral(
                1))),
          IntLiteral(
            9)),
        IntLiteral(
          10)),
      CallStatement(
        check,
        Arguments(
          VariableExpression(
            ArrayAccess(
              ArrayAccess(
                NamedVariable(
                  m),
                IntLiteral(
                  0)),
              IntLiteral(
                7))),
          VariableExpression(
            ArrayAccess(
              ArrayAccess(
                NamedVariable(
                  m),
                IntLiteral(
                  1)),
              IntLiteral(
                8))),
          BinaryExpression(
            SUB,
            IntLiteral(
              0),
            IntLiteral(
              2)),
          IntLiteral(
            135))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            ArrayAccess(
              ArrayAccess(
                NamedVariable(
                  m),
                IntLiteral(
                  0)),
              IntLiteral(
                7))))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            ArrayAccess(
              ArrayAccess(
                NamedVariable(
                  m),
                IntLiteral(
                  1)),
              IntLiteral(
                8))))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      CallStatement(
        ausgabe,
        Arguments(
          IntLiteral(
            2))),
      CallStatement(
        callbyval,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        check,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)),
          BinaryExpression(
            SUB,
            IntLiteral(
              0),
            IntLiteral(
              1)),
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      CallStatement(
        callbyref,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        check,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)),
          IntLiteral(
            0),
          IntLiteral(
            33))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      AssignStatement(
        ArrayAccess(
          NamedVariable(
            n),
          IntLiteral(
            0)),
        IntLiteral(
          5)),
      AssignStatement(
        ArrayAccess(
          NamedVariable(
            n),
          IntLiteral(
            1)),
        IntLiteral(
          4)),
      AssignStatement(
        ArrayAccess(
          NamedVariable(
            n),
          IntLiteral(
            2)),
        IntLiteral(
          3)),
      AssignStatement(
        ArrayAccess(
          NamedVariable(
            n),
          IntLiteral(
            3)),
        IntLiteral(
          2)),
      AssignStatement(
        ArrayAccess(
          NamedVariable(
            n),
          IntLiteral(
            4)),
        IntLiteral(
          1)),
      CallStatement(
        callArray,
        Arguments(
          VariableExpression(
            NamedVariable(
              n)))),
      CallStatement(
        check,
        Arguments(
          VariableExpression(
            ArrayAccess(
              NamedVariable(
                n),
              IntLiteral(
                0))),
          VariableExpression(
            ArrayAccess(
              NamedVariable(
                n),
              IntLiteral(
                4))),
          IntLiteral(
            99),
          IntLiteral(
            66))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            ArrayAccess(
              NamedVariable(
                n),
              IntLiteral(
                0))))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            ArrayAccess(
              NamedVariable(
                n),
              IntLiteral(
                4))))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      AssignStatement(
        NamedVariable(
          i),
        IntLiteral(
          1)),
      AssignStatement(
        NamedVariable(
          j),
        IntLiteral(
          1)),
      CallStatement(
        callRecursive,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        check,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j)),
          IntLiteral(
            1),
          IntLiteral(
            67))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      CallStatement(
        ausgabe,
        Arguments(
          IntLiteral(
            3))),
      CompoundStatement(
        EmptyStatement(),
        EmptyStatement(),
        EmptyStatement()),
      AssignStatement(
        NamedVariable(
          i),
        IntLiteral(
          0)),
      WhileStatement(
        BinaryExpression(
          LSE,
          VariableExpression(
            NamedVariable(
              i)),
          IntLiteral(
            3)),
        CompoundStatement(
          AssignStatement(
            NamedVariable(
              j),
            BinaryExpression(
              ADD,
              BinaryExpression(
                MUL,
                IntLiteral(
                  2),
                VariableExpression(
                  NamedVariable(
                    i))),
              IntLiteral(
                1))),
          AssignStatement(
            ArrayAccess(
              NamedVariable(
                k),
              VariableExpression(
                NamedVariable(
                  i))),
            BinaryExpression(
              MUL,
              VariableExpression(
                NamedVariable(
                  j)),
              BinaryExpression(
                DIV,
                BinaryExpression(
                  DIV,
                  BinaryExpression(
                    ADD,
                    BinaryExpression(
                      MUL,
                      BinaryExpression(
                        ADD,
                        VariableExpression(
                          NamedVariable(
                            j)),
                        VariableExpression(
                          NamedVariable(
                            j))),
                      VariableExpression(
                        NamedVariable(
                          j))),
                    BinaryExpression(
                      MUL,
                      VariableExpression(
                        NamedVariable(
                          j)),
                      BinaryExpression(
                        ADD,
                        VariableExpression(
                          NamedVariable(
                            j)),
                        BinaryExpression(
                          MUL,
                          VariableExpression(
                            NamedVariable(
                              j)),
                          BinaryExpression(
                            ADD,
                            VariableExpression(
                              NamedVariable(
                                j)),
                            VariableExpression(
                              NamedVariable(
                                j))))))),
                  VariableExpression(
                    NamedVariable(
                      j))),
                VariableExpression(
                  NamedVariable(
                    j))))),
          AssignStatement(
            ArrayAccess(
              NamedVariable(
                k),
              IntLiteral(
                0)),
            BinaryExpression(
              ADD,
              VariableExpression(
                ArrayAccess(
                  NamedVariable(
                    k),
                  IntLiteral(
                    0))),
              VariableExpression(
                ArrayAccess(
                  NamedVariable(
                    k),
                  VariableExpression(
                    NamedVariable(
                      i)))))),
          CallStatement(
            printi,
            Arguments(
              VariableExpression(
                NamedVariable(
                  i)))),
          CallStatement(
            printc,
            Arguments(
              IntLiteral(
                32))),
          CallStatement(
            printi,
            Arguments(
              VariableExpression(
                ArrayAccess(
                  NamedVariable(
                    k),
                  VariableExpression(
                    NamedVariable(
                      i)))))),
          CallStatement(
            printc,
            Arguments(
              IntLiteral(
                10))),
          AssignStatement(
            NamedVariable(
              i),
            BinaryExpression(
              ADD,
              VariableExpression(
                NamedVariable(
                  i)),
              IntLiteral(
                1))))),
      CallStatement(
        check,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            ArrayAccess(
              NamedVariable(
                k),
              IntLiteral(
                0))),
          IntLiteral(
            4),
          IntLiteral(
            221))),
      AssignStatement(
        NamedVariable(
          i),
        IntLiteral(
          0)),
      AssignStatement(
        NamedVariable(
          j),
        IntLiteral(
          1)),
      IfStatement(
        BinaryExpression(
          EQU,
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              j))),
        IfStatement(
          BinaryExpression(
            NEQ,
            VariableExpression(
              NamedVariable(
                i)),
            BinaryExpression(
              SUB,
              VariableExpression(
                NamedVariable(
                  j)),
              IntLiteral(
                1))),
          CompoundStatement(
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  101))),
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  114))),
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  114))),
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  111))),
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  114)))),
          CompoundStatement(
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  101))),
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  114))),
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  114))),
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  111))),
            CallStatement(
              printc,
              Arguments(
                IntLiteral(
                  114))))),
        CompoundStatement(
          CallStatement(
            printc,
            Arguments(
              IntLiteral(
                111))),
          CallStatement(
            printc,
            Arguments(
              IntLiteral(
                107))),
          EmptyStatement())),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      CallStatement(
        ausgabe,
        Arguments(
          IntLiteral(
            4))),
      CallStatement(
        manyargs,
        Arguments(
          IntLiteral(
            1),
          IntLiteral(
            3),
          VariableExpression(
            NamedVariable(
              t)),
          VariableExpression(
            NamedVariable(
              j)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))))),
  ProcedureDeclaration(
    ausgabe,
    Parameters(
      ParameterDeclaration(
        nummer,
        NamedTypeExpression(
          int),
        false)),
    Variables(),
    Body(
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            84))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            101))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            115))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            116))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            32))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              nummer)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))))),
  ProcedureDeclaration(
    check,
    Parameters(
      ParameterDeclaration(
        i,
        NamedTypeExpression(
          int),
        false),
      ParameterDeclaration(
        j,
        NamedTypeExpression(
          int),
        false),
      ParameterDeclaration(
        expectedI,
        NamedTypeExpression(
          int),
        false),
      ParameterDeclaration(
        expectedJ,
        NamedTypeExpression(
          int),
        false)),
    Variables(),
    Body(
      IfStatement(
        BinaryExpression(
          NEQ,
          VariableExpression(
            NamedVariable(
              i)),
          VariableExpression(
            NamedVariable(
              expectedI))),
        CallStatement(
          error,
          Arguments(
            VariableExpression(
              NamedVariable(
                i)),
            VariableExpression(
              NamedVariable(
                expectedI)))),
        EmptyStatement()),
      IfStatement(
        BinaryExpression(
          NEQ,
          VariableExpression(
            NamedVariable(
              j)),
          VariableExpression(
            NamedVariable(
              expectedJ))),
        CallStatement(
          error,
          Arguments(
            VariableExpression(
              NamedVariable(
                j)),
            VariableExpression(
              NamedVariable(
                expectedJ)))),
        EmptyStatement()))),
  ProcedureDeclaration(
    error,
    Parameters(
      ParameterDeclaration(
        i,
        NamedTypeExpression(
          int),
        false),
      ParameterDeclaration(
        expectedI,
        NamedTypeExpression(
          int),
        false)),
    Variables(),
    Body(
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            69))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            114))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            114))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            111))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            114))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            58))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            105))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            61))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              i)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            44))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            69))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            120))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            112))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            101))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            99))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            116))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            101))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            100))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            58))),
      CallStatement(
        printi,
        Arguments(
          VariableExpression(
            NamedVariable(
              expectedI)))),
      CallStatement(
        printc,
        Arguments(
          IntLiteral(
            10))))))

